name: autocommitTest

on: 
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: '**/package-lock.json'
          cache: npm

      - name: Install dependencies & build
        run: npm ci && npm run build

        # sets 'changes_detected' to 'true' if there are changes in the dist folder
      - name: commit dist 
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'dist/**'
          commit_message: 'dist folder autobuild'

      - name: log if changes
        env: 
          changes_detected: ${{ steps.commit.outputs.changes_detected }}
        run: |
          if [ "$changes_detected" == "true" ]; then
            echo "Typescript changes detected. Dist folder has been autobuilt and committed."
            echo ":package: Typescript changes detected. Dist folder has been autobuilt and committed." >> $GITHUB_STEP_SUMMARY
          else
            echo "No typescript changes detected"
            echo ":memo: No typescript changes detected. No new commit." >> $GITHUB_STEP_SUMMARY
          fi
          