name: autocommitTest

on: 
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies & build
        run: npm ci && npm run build
        
      - name: commit dist 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'dist/**'
          tagging_message: 'autobuild'
